[pytest]
# This repo is a suite/monorepo. Only some subprojects have managed Python deps.
# Limit default collection to the projects we actively maintain here.
testpaths =
    StatiBaker/tests
    fuzzymodo/tests
    casey-git-clone/tests

addopts = -q --import-mode=importlib
